CirculationSettings:
  description: Circulation Settings in a data tenant
  type: "object"
  properties:
    id:
      description: "ID of the Circulation Settings"
      $ref: "common/uuid.yaml"
    name:
      description: "Name of the Circulation Settings"
      $ref: "common/uuid.yaml"
    value:
      description: "Value of the Circulation Settings"
      type: string
  required:
    - id
    - name
    - value
