server:
  port: 8081
spring:
  application:
    name: mod-circulation-bff
  autoconfigure:
    exclude: |-
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  liquibase:
    enabled: false
  mustache:
    check-template-location: false
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  cloud:
    openfeign:
      okhttp:
        enabled: true
folio:
  tenant:
    validation:
      enabled: true
  environment: ${ENV:folio}
  okapi-url: ${OKAPI_URL:http://okapi:9130}
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace
      base-path: /admin
  #  endpoint:
  #    health:
  #      show-details: always
  #      show-components: always
  ###################################################
  # Disable all checks except for readiness
  ###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
debug: false