server:
  port: 8081
spring:
  application:
    name: mod-circulation-bff
  autoconfigure:
    exclude: |-
      org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,
      org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,
      org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration
  liquibase:
    enabled: false
  mustache:
    check-template-location: false
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
folio:
  tenant:
    secure-tenant-id: ${SECURE_TENANT_ID}
    validation:
      enabled: true
  environment: ${ENV:folio}
  okapi-url: ${OKAPI_URL:http://okapi:9130}
  system-user:
    enabled: ${SYSTEM_USER_ENABLED:true}
    username: ${SYSTEM_USER_NAME:mod-circulation-bff}
    password: ${SYSTEM_USER_PASSWORD:mod-circulation-bff}
    lastname: System
    permissionsFilePath: permissions/mod-circulation-bff.csv
  batch-requests:
    query-request-ids-count: ${BATCH_REQUEST_DETAILS_QUERY_IDS_COUNT:20}
  exchange:
    enabled: true
  logging: # https://github.com/folio-org/folio-spring-support/blob/master/doc/REQUEST_LOGGING.md
    request:
      enabled: false # Logs incoming HTTP requests
      level: BASIC
    exchange:
      enabled: false # Logs outgoing requests
      level: BASIC
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace
      base-path: /admin
  #  endpoint:
  #    health:
  #      show-details: always
  #      show-components: always
  ###################################################
  # Disable all checks except for readiness
  ###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
debug: false
logging:
  level:
    org.folio.spring.client.ExchangeLoggingInterceptor: DEBUG
    org.folio.spring.filter.LoggingRequestFilter: DEBUG