openapi: 3.0.0
info:
  title: Circulation BFF requests API
  version: v1
paths:
  /circulation-bff/requests/allowed-service-points:
    $ref: 'paths/allowedServicePoints.yaml'
  /circulation-bff/requests/search-instances:
    $ref: 'paths/searchInstances.yaml'
  /circulation-bff/mediated-requests/confirm:
    $ref: 'paths/confirmMediatedRequests.yaml'
  /circulation-bff/requests:
    $ref: 'paths/requests.yaml'
  /circulation-bff/batch-requests:
    $ref: 'paths/multiItemBatchRequest.yaml'
  /circulation-bff/batch-requests/{batchId}:
    $ref: 'paths/getMultiItemBatchRequest.yaml'
  /circulation-bff/batch-requests/{batchId}/details:
    $ref: 'paths/getMultiItemBatchRequestDetails.yaml'
  /circulation-bff/loans:
    $ref: 'paths/loans.yaml'
  /circulation-bff/loans/{loanId}:
    $ref: 'paths/loanById.yaml'
  /circulation-bff/external-users/{externalUserId}/tenant/{tenantId}:
    $ref: 'paths/externalUser.yaml'
  /circulation-bff/pick-slips/{servicePointId}:
    $ref: 'paths/pickSlips.yaml'
  /circulation-bff/search-slips/{servicePointId}:
    $ref: 'paths/searchSlips.yaml'
  /circulation-bff/create-ecs-request-external:
    $ref: 'paths/ecsRequestExternal.yaml'
  /circulation-bff/loans/check-in-by-barcode:
    $ref: 'paths/checkIn.yaml'
  /circulation-bff/loans/check-out-by-barcode:
    $ref: 'paths/checkOut.yaml'
  /circulation-bff/loans/{loanId}/declare-item-lost:
    $ref: 'paths/declareItemLost.yaml'
  /circulation-bff/loans/{loanId}/claim-item-returned:
    $ref: 'paths/claimItemReturned.yaml'
  /circulation-bff/loans/{loanId}/declare-claimed-returned-item-as-missing:
    $ref: 'paths/declareClaimedReturnedItemAsMissing.yaml'
  /circulation-bff/inventory/items:
    $ref: 'paths/inventoryItems.yaml'
components:
  schemas:
    tlrSettings:
      $ref: 'schemas/dto/tlrSettings.yaml'
    circulationSettingsResponse:
      $ref: 'schemas/dto/circulationSettingsResponse.yaml'
    userTenantCollection:
      $ref: 'schemas/dto/userTenantCollection.yaml'
    item:
      $ref: 'schemas/dto/inventoryStorage/item.json'
    items:
      $ref: 'schemas/dto/inventoryStorage/items.json'
    holdingsRecords:
      $ref: 'schemas/dto/inventoryStorage/holdingsRecords.json'
    instances:
      $ref: 'schemas/dto/inventoryStorage/instances.json'
    locations:
      $ref: 'schemas/dto/inventoryStorage/locations.json'
    libraries:
      $ref: 'schemas/dto/inventoryStorage/libraries.json'
    campuses:
      $ref: 'schemas/dto/inventoryStorage/campuses.json'
    institutions:
      $ref: 'schemas/dto/inventoryStorage/institutions.json'
    servicePoints:
      $ref: 'schemas/dto/inventoryStorage/servicePoints.json'
    loanTypes:
      $ref: 'schemas/dto/inventoryStorage/loanTypes.json'
    materialTypes:
      $ref: 'schemas/dto/inventoryStorage/materialTypes.json'
    searchInstances:
      $ref: 'schemas/dto/search/searchInstances.yaml'
    patronGroup:
      $ref: 'schemas/dto/request/patronGroup.yaml'
    request:
      $ref: 'schemas/dto/request/request.yaml'
    requests:
      $ref: 'schemas/dto/request/requests.yaml'
    bffRequest:
      $ref: 'schemas/dto/request/bffRequest.yaml'
    ecsTlr:
      $ref: 'schemas/dto/ecsTlr/ecsTlr.yaml'
    circulationItem:
      $ref: 'schemas/dto/circulationItem/circulationItem.yaml'
    consortiumItem:
      $ref: 'schemas/dto/search/consortiumItem.yaml'
    loans:
      $ref: 'schemas/dto/circulation/loans.json'
    declareItemLostRequest:
      $ref: 'schemas/dto/circulation/declareItemLostRequest.yaml'
    tlrDeclareItemLostRequest:
      $ref: 'schemas/dto/ecsTlr/tlrDeclareItemLostRequest.yaml'
    claimItemReturnedRequest:
      $ref: 'schemas/dto/circulation/claimItemReturnedRequest.yaml'
    tlrClaimItemReturnedRequest:
      $ref: 'schemas/dto/ecsTlr/tlrClaimItemReturnedRequest.yaml'
    tlrDeclareClaimedReturnedItemAsMissing:
      $ref: 'schemas/dto/ecsTlr/tlrDeclareClaimedReturnedItemAsMissingRequest.yaml'
    inventoryItem:
      $ref: 'schemas/dto/inventory/inventoryItem.json'
    inventoryItems:
      $ref: 'schemas/dto/inventory/inventoryItems.json'
