openapi: 3.0.0
info:
  title: Circulation BFF requests API
  version: v1
paths:
  /circulation-bff/requests/allowed-service-points:
    $ref: 'paths/allowedServicePoints/allowedServicePoints.yaml'
  /circulation-bff/requests/search-instances:
    $ref: 'paths/searchInstances/searchInstances.yaml'
  /circulation-bff/mediated-requests/confirm:
    $ref: 'paths/mediatedRequests/confirmMediatedRequests.yaml'
  /circulation-bff/external-users/{externalUserId}/tenant/{tenantId}:
    $ref: 'paths/externalUser/externalUser.yaml'

components:
  schemas:
    tlr-settings:
      $ref: 'schemas/dto/TlrSettings.yaml#/TlrSettings'
    circulationSettingsResponse:
      $ref: 'schemas/response/circulationSettingsResponse.yaml'
    userTenantCollection:
      $ref: 'schemas/dto/UserTenantCollection.yaml#/UserTenantCollection'
    userCollection:
      $ref: 'schemas/dto/userCollection.json'
    items:
      $ref: 'schemas/dto/inventory/items.json'
    holdings-records:
      $ref: 'schemas/dto/inventory/holdingsRecords.json'
    instances:
      $ref: 'schemas/dto/inventory/instances.json'
    locations:
      $ref: 'schemas/dto/inventory/locations.json'
    service-points:
      $ref: 'schemas/dto/inventory/servicePoints.json'
    material-types:
      $ref: 'schemas/dto/inventory/materialTypes.json'
    search-instances:
      $ref: 'schemas/dto/search/searchInstances.yaml'