openapi: 3.0.0
info:
  title: Circulation BFF requests API
  version: v1
paths:
  /circulation-bff/requests/allowed-service-points:
    $ref: 'paths/allowedServicePoints/allowedServicePoints.yaml'
  /circulation-bff/requests/search-instances:
    $ref: 'paths/searchInstances/searchInstances.yaml'
components:
  schemas:
    tlr-settings:
      $ref: 'schemas/dto/TlrSettings.yaml#/TlrSettings'
    circulationSettingsResponse:
      $ref: 'schemas/response/circulationSettingsResponse.yaml'
    userTenantCollection:
      $ref: 'schemas/dto/UserTenantCollection.yaml#/UserTenantCollection'
