openapi: 3.0.0
info:
  title: Circulation BFF requests API
  version: v1
paths:
  /circulation-bff/requests/allowed-service-points:
    $ref: 'paths/allowedServicePoints/allowedServicePoints.yaml'
  /circulation-bff/requests/search-instances:
    $ref: 'paths/searchInstances/searchInstances.yaml'
  /circulation-bff/mediated-requests/confirm:
    $ref: 'paths/mediatedRequests/confirmMediatedRequests.yaml'
  /circulation-bff/requests:
    $ref: 'paths/requests/requests.yaml'
  /circulation-bff/loans:
    $ref: 'paths/loans/loans.yaml'
  /circulation-bff/loans/{loanId}:
    $ref: 'paths/loans/loanById.yaml'
  /circulation-bff/external-users/{externalUserId}/tenant/{tenantId}:
    $ref: 'paths/externalUser/externalUser.yaml'
  /circulation-bff/pick-slips/{servicePointId}:
    $ref: 'paths/staffSlips/pickSlips.yaml'
  /circulation-bff/search-slips/{servicePointId}:
    $ref: 'paths/staffSlips/searchSlips.yaml'
  /circulation-bff/create-ecs-request-external:
    $ref: 'paths/ecsRequestExternal/ecsRequestExternal.yaml'
  /circulation-bff/loans/check-in-by-barcode:
    $ref: 'paths/checkIn/checkIn.yaml'
  /circulation-bff/loans/check-out-by-barcode:
    $ref: 'paths/checkOut/checkOut.yaml'
  /circulation-bff/loans/{loanId}/declare-item-lost:
    $ref: 'paths/declareItemLost/declareItemLost.yaml'
  /circulation-bff/loans/{loanId}/claim-item-returned:
    $ref: 'paths/claimItemReturned/claimItemReturned.yaml'
components:
  schemas:
    tlrSettings:
      $ref: 'schemas/dto/tlrSettings.yaml'
    circulationSettingsResponse:
      $ref: 'schemas/dto/circulationSettingsResponse.yaml'
    userTenantCollection:
      $ref: 'schemas/dto/userTenantCollection.yaml'
    items:
      $ref: 'schemas/dto/inventory/items.json'
    holdingsRecords:
      $ref: 'schemas/dto/inventory/holdingsRecords.json'
    instances:
      $ref: 'schemas/dto/inventory/instances.json'
    locations:
      $ref: 'schemas/dto/inventory/locations.json'
    libraries:
      $ref: 'schemas/dto/inventory/libraries.json'
    campuses:
      $ref: 'schemas/dto/inventory/campuses.json'
    institutions:
      $ref: 'schemas/dto/inventory/institutions.json'
    servicePoints:
      $ref: 'schemas/dto/inventory/servicePoints.json'
    loanTypes:
      $ref: 'schemas/dto/inventory/loanTypes.json'
    materialTypes:
      $ref: 'schemas/dto/inventory/materialTypes.json'
    searchInstances:
      $ref: 'schemas/dto/search/searchInstances.yaml'
    patronGroup:
      $ref: 'schemas/dto/request/patronGroup.yaml'
    request:
      $ref: 'schemas/dto/request/request.yaml'
    bffRequest:
      $ref: 'schemas/dto/request/bffRequest.yaml'
    ecsTlr:
      $ref: 'schemas/dto/ecsTlr/ecsTlr.yaml'
    circulationItem:
      $ref: 'schemas/dto/circulationItem/circulationItem.yaml'
    consortiumItem:
      $ref: 'schemas/dto/search/consortiumItem.yaml'
    loans:
      $ref: 'schemas/dto/circulation/loans.json'
    declareItemLostRequest:
      $ref: 'schemas/dto/circulation/declareItemLostRequest.yaml'
    tlrDeclareItemLostRequest:
      $ref: 'schemas/dto/ecsTlr/tlrDeclareItemLostRequest.yaml'
    claimItemReturnedRequest:
      $ref: 'schemas/dto/circulation/claimItemReturnedRequest.yaml'
    tlrClaimItemReturnedRequest:
      $ref: 'schemas/dto/ecsTlr/tlrClaimItemReturnedRequest.yaml'
